/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logic.Producto;

/**
 *
 * @author facun
 */
public class PantallaNuevoProducto extends javax.swing.JFrame {

    private List<Producto> productos = new ArrayList<>();

    /**
     * Creates new form PantallaNuevoPRoducto
     */
    public PantallaNuevoProducto(List<Producto> listaProductos) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.productos = listaProductos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblCodigoProducto1 = new javax.swing.JLabel();
        txtCodigoProducto1 = new javax.swing.JTextField();
        lblMarca1 = new javax.swing.JLabel();
        txtMarca1 = new javax.swing.JTextField();
        lblDescripcion1 = new javax.swing.JLabel();
        txtDescripcion1 = new javax.swing.JTextField();
        lblCosto1 = new javax.swing.JLabel();
        txtCosto1 = new javax.swing.JTextField();
        lblPorcentaje1 = new javax.swing.JLabel();
        txtPorcentaje1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setEnabled(false);

        lblCodigoProducto1.setText("Codigo de producto");

        lblMarca1.setText("Marca");

        lblDescripcion1.setText("Descripcion");

        txtDescripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcion1ActionPerformed(evt);
            }
        });

        lblCosto1.setText("Costo");

        lblPorcentaje1.setText("Porcentaje de ganancia");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("NUEVO PRODUCTO");

        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 221, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCosto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMarca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPorcentaje1)
                                    .addComponent(lblCodigoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCosto1)
                            .addComponent(txtDescripcion1)
                            .addComponent(txtMarca1)
                            .addComponent(txtCodigoProducto1)
                            .addComponent(txtPorcentaje1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnLimpiar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoProducto1)
                    .addComponent(txtCodigoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca1)
                    .addComponent(txtMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion1)
                            .addComponent(txtDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCosto1)
                            .addComponent(txtCosto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnLimpiar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentaje1)
                    .addComponent(txtPorcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcion1ActionPerformed

    }//GEN-LAST:event_txtDescripcion1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        this.txtCodigoProducto1.setText("");
        this.txtCosto1.setText("");
        this.txtDescripcion1.setText("");
        this.txtMarca1.setText("");
        this.txtPorcentaje1.setText("");
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        int codigoProducto = 0;
        float costo = 0;
        int porc_ganancia = 0;

        StringBuilder mensajeError = new StringBuilder();

        try {
            codigoProducto = Integer.parseInt(this.txtCodigoProducto1.getText());
            // Realizar acciones con el código del producto
        } catch (NumberFormatException eCodigo) {
            mensajeError.append("El formato del código de producto es incorrecto. Debe ser un número entero.\n");
        }

        try {
            costo = Float.parseFloat(this.txtCosto1.getText());
            // Realizar acciones con el costo
        } catch (NumberFormatException eCosto) {
            mensajeError.append("El formato del costo es incorrecto. Debe ser un número decimal.\n");
        }

        try {
            porc_ganancia = Integer.parseInt(this.txtPorcentaje1.getText());
            // Realizar acciones con porc_ganancia
        } catch (NumberFormatException ePorcentaje) {
            mensajeError.append("El formato del porcentaje de ganancia es incorrecto. Debe ser un número entero.\n");
        }

        String marca = this.txtMarca1.getText();
        String descripcion = this.txtDescripcion1.getText();

        boolean cargaCorrecta = true;

        if (codigoProducto < 1 || codigoProducto > 99999) {
            mensajeError.append("Código incorrecto. Debe estar entre 1 y 99999.\n");
            cargaCorrecta = false;
        }
        for (Producto producto : productos) {
            if (producto.getCodigoProducto() == codigoProducto) {
                mensajeError.append("Código existente.\n");
                cargaCorrecta = false;
                break; // No es necesario seguir buscando
            }
        }

        if (marca.length() > 10 || marca.isEmpty()) {
            mensajeError.append("La marca debe tener un máximo de 10 caracteres y no puede estar vacía.\n");
            cargaCorrecta = false;
        }

        if (descripcion.length() > 20 || descripcion.isEmpty()) {
            mensajeError.append("La descripción debe tener un máximo de 20 caracteres y no puede estar vacía.\n");
            cargaCorrecta = false;
        }

        if (costo <= 0) {
            mensajeError.append("El costo no puede ser menor o igual a cero.\n");
            cargaCorrecta = false;
        }

        if (porc_ganancia <= 0) {
            mensajeError.append("El porcentaje de ganancia no puede ser menor o igual a cero.\n");
            cargaCorrecta = false;
        }

        if (cargaCorrecta) {
            Producto nuevoProducto = new Producto(codigoProducto, marca, descripcion, costo, porc_ganancia);
            productos.add(nuevoProducto);
            JOptionPane.showMessageDialog(PantallaNuevoProducto.this, "Carga exitosa del producto.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(PantallaNuevoProducto.this, "Datos incorrectos. Reintente:\n" + mensajeError.toString(), "Errores", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblCodigoProducto1;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblPorcentaje1;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtCodigoProducto1;
    private javax.swing.JTextField txtCosto1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescripcion1;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMarca1;
    private javax.swing.JTextField txtPorcentaje1;
    // End of variables declaration//GEN-END:variables
}
